CREATE DATABASE DB_EMPENHOS;
USE DB_EMPENHOS;

-- Tabela de Documentos
CREATE TABLE TB_DOCUMENTO (
    DOC_ID INT PRIMARY KEY AUTO_INCREMENT,
    DOC_CODTIPO VARCHAR(2),
    DOC_TIPO VARCHAR(100)
);

-- Tabela de Órgãos
CREATE TABLE TB_ORGAO (
    ORG_ID INT PRIMARY KEY AUTO_INCREMENT,
    ORG_CODIGO INT,
    ORG_NOME VARCHAR(255)
);

-- Tabela de Unidades Gestoras
CREATE TABLE TB_UNIDADE_GESTORA (
    UGE_ID INT PRIMARY KEY AUTO_INCREMENT,
    UGE_CODIGO INT,
    UGE_NOME VARCHAR(255)
);

-- Tabela de Gestões
CREATE TABLE TB_GESTAO (
    GES_ID INT PRIMARY KEY AUTO_INCREMENT,
    GES_CODIGO INT,
    GES_NOME VARCHAR(255)
);

-- Tabela de Favorecidos
CREATE TABLE TB_FAVORECIDO (
    FAV_ID INT PRIMARY KEY AUTO_INCREMENT,
    FAV_CODIGO VARCHAR(100),
    FAV_NOME VARCHAR(255)
);

-- Tabela de Esferas Orçamentárias
CREATE TABLE TB_ESFERA_ORCAMENTARIA (
    EOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    EOR_CODIGO INT,
    EOR_DESCRICAO VARCHAR(255)
);

-- Tabela de Tipos de Crédito
CREATE TABLE TB_TIPO_CREDITO (
    TCR_ID INT PRIMARY KEY AUTO_INCREMENT,
    TCR_CODIGO CHAR(1),
    TCR_DESCRICAO VARCHAR(255)
);

-- Tabela de Grupos de Fontes de Recurso
CREATE TABLE TB_GRUPO_FONTE_RECURSO (
    GFR_ID INT PRIMARY KEY AUTO_INCREMENT,
    GFR_CODIGO INT,
    GFR_DESCRICAO VARCHAR(255)
);

-- Tabela de Fontes de Recurso
CREATE TABLE TB_FONTE_RECURSO (
    FRE_ID INT PRIMARY KEY AUTO_INCREMENT,
    FRE_CODIGO INT,
    FRE_DESCRICAO VARCHAR(255)
);

-- Tabela de Unidade orçamentária
CREATE TABLE TB_UNIDADE_ORCAMENTARIA (
    UOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    UOR_CODIGO INT,
    UOR_DESCRICAO VARCHAR(255)
);

-- Tabela de Funções
CREATE TABLE TB_FUNCAO (
    FUN_ID INT PRIMARY KEY AUTO_INCREMENT,
    FUN_CODIGO INT,
    FUN_DESCRICAO VARCHAR(255)
);

-- Tabela de Sub Funções
CREATE TABLE TB_SUB_FUNCAO (
    SFU_ID INT PRIMARY KEY AUTO_INCREMENT,
    SFU_CODIGO INT,
    SFU_DESCRICAO VARCHAR(255)
);

-- Tabela de Programa
CREATE TABLE TB_PROGRAMA (
    PRO_ID INT PRIMARY KEY AUTO_INCREMENT,
    PRO_CODIGO INT,
    PRO_NOME VARCHAR(255)
);

-- Tabela de Ação
CREATE TABLE TB_ACAO (
    ACA_ID INT PRIMARY KEY AUTO_INCREMENT,
    ACA_CODIGO VARCHAR(100),
    ACA_NOME VARCHAR(255)
);

-- Tabela de Linguagem Cidadã
CREATE TABLE TB_LINGUAGEM_CIDADA (
    LCI_ID INT PRIMARY KEY AUTO_INCREMENT,
    LCI_DESCRICAO VARCHAR(255)
);

-- Tabela de Subtítulo
CREATE TABLE TB_SUBTITULO (
    SUB_ID INT PRIMARY KEY AUTO_INCREMENT,
    SUB_CODIGO VARCHAR(100),
    SUB_DESCRICAO VARCHAR(255)
);

-- Tabela de Plano Orçamentário
CREATE TABLE TB_PLANO_ORCAMENTARIO (
    POR_ID INT PRIMARY KEY AUTO_INCREMENT,
    POR_CODIGO INT,
    POR_DESCRICAO VARCHAR(255)
);

-- Tabela de Programa Governo
CREATE TABLE TB_PROGRAMA_GOVERNO (
    PGO_ID INT PRIMARY KEY AUTO_INCREMENT,
    PGO_CODIGO INT,
    PGO_NOME VARCHAR(255)
);

-- Tabela de Autor Emenda
CREATE TABLE TB_AUTOR_EMENDA (
    AEM_ID INT PRIMARY KEY AUTO_INCREMENT,
    AEM_NOME VARCHAR(255)
);

-- Tabela de Categoria de Despesa
CREATE TABLE TB_CATEGORIA_DESPESA (
    CDE_ID INT PRIMARY KEY AUTO_INCREMENT,
    CDE_CODIGO INT,
    CDE_NOME VARCHAR(255)
);

-- Tabela de Grupo de Despesa
CREATE TABLE TB_GRUPO_DESPESA (
    GDE_ID INT PRIMARY KEY AUTO_INCREMENT,
    GDE_CODIGO INT,
    GDE_NOME VARCHAR(255)
);

-- Tabela de Modalidade
CREATE TABLE TB_MODALIDADE (
    MOD_ID INT PRIMARY KEY AUTO_INCREMENT,
    MOD_CODIGO INT,
    MOD_NOME VARCHAR(255)
);

-- Tabela de Elemento de Despesa
CREATE TABLE TB_ELEMENTO_DESPESA (
    EDE_ID INT PRIMARY KEY AUTO_INCREMENT,
    EDE_CODIGO INT,
    EDE_NOME VARCHAR(255)
);

-- Tabela de Empenhos
CREATE TABLE TB_EMPENHO (
    EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_CODIGO VARCHAR(255) NOT NULL,
    EMP_CODRESUMIDO VARCHAR(100) NOT NULL,
    EMP_DATA_EMISSAO DATE NOT NULL,
    EMP_TIPO VARCHAR(50) NOT NULL,
    EMP_ESPECIE VARCHAR(50) NOT NULL,
    EMP_OBSERVACAO TEXT,
    EMP_PROCESSO VARCHAR(255) NULL,
    EMP_MODALIDADE_LICITACAO VARCHAR(100) NOT NULL,
    EMP_INCISO VARCHAR(100) NOT NULL,
    EMP_AMPARO VARCHAR(100) NOT NULL,
    EMP_REF_DISP_INEX INT NOT NULL,
    EMP_CODIGO_CONVENIO INT NOT NULL,
    EMP_CONTRATO VARCHAR(100) NOT NULL,
    EMP_VALOR_ORIGINAL DECIMAL(15, 2) NOT NULL,
    EMP_VALOR_CONVERTIDO DECIMAL(15, 2) NOT NULL,
    EMP_VALOR_CONVERSAO DECIMAL(15, 2) NOT NULL,
    EMP_DOCID INT NOT NULL,
    EMP_ORGSUPID INT NOT NULL,
    EMP_ORGID INT NOT NULL,
    EMP_UGEID INT NOT NULL,
    EMP_GESID INT NOT NULL,
    EMP_FAVID INT NOT NULL,
    EMP_EORID INT NOT NULL,
    EMP_TCRID INT NOT NULL,
    EMP_GFRID INT NOT NULL,
    EMP_FREID INT NOT NULL,
    EMP_UORID INT NOT NULL,
    EMP_FUNID INT NOT NULL,
    EMP_SFUID INT NOT NULL,
    EMP_PROID INT NOT NULL,
    EMP_ACAID INT NOT NULL,
    EMP_LCIID INT NULL,
    EMP_SUBID INT NOT NULL,
    EMP_PORID INT NOT NULL,
    EMP_PGOID INT NOT NULL,
    EMP_AEMID INT NOT NULL,
    EMP_CDEID INT NOT NULL, 
    EMP_GDEID INT NOT NULL,
    EMP_MODID INT NOT NULL,
    EMP_EDEID INT NOT NULL,
    FOREIGN KEY (EMP_DOCID) REFERENCES TB_DOCUMENTO (DOC_ID),
    FOREIGN KEY (EMP_ORGSUPID) REFERENCES TB_ORGAO (ORG_ID),
    FOREIGN KEY (EMP_ORGID) REFERENCES TB_ORGAO (ORG_ID),
    FOREIGN KEY (EMP_UGEID) REFERENCES TB_UNIDADE_GESTORA (UGE_ID),
    FOREIGN KEY (EMP_GESID) REFERENCES TB_GESTAO (GES_ID),
    FOREIGN KEY (EMP_FAVID) REFERENCES TB_FAVORECIDO (FAV_ID),
    FOREIGN KEY (EMP_EORID) REFERENCES TB_ESFERA_ORCAMENTARIA (EOR_ID),
    FOREIGN KEY (EMP_TCRID) REFERENCES TB_TIPO_CREDITO (TCR_ID),
    FOREIGN KEY (EMP_GFRID) REFERENCES TB_GRUPO_FONTE_RECURSO (GFR_ID),
    FOREIGN KEY (EMP_FREID) REFERENCES TB_FONTE_RECURSO (FRE_ID),
    FOREIGN KEY (EMP_UORID) REFERENCES TB_UNIDADE_ORCAMENTARIA (UOR_ID),
    FOREIGN KEY (EMP_FUNID) REFERENCES TB_FUNCAO (FUN_ID),
    FOREIGN KEY (EMP_SFUID) REFERENCES TB_SUB_FUNCAO (SFU_ID),
    FOREIGN KEY (EMP_PROID) REFERENCES TB_PROGRAMA (PRO_ID),
    FOREIGN KEY (EMP_ACAID) REFERENCES TB_ACAO (ACA_ID),
    FOREIGN KEY (EMP_LCIID) REFERENCES TB_LINGUAGEM_CIDADA (LCI_ID),
    FOREIGN KEY (EMP_SUBID) REFERENCES TB_SUBTITULO (SUB_ID),
    FOREIGN KEY (EMP_PORID) REFERENCES TB_PLANO_ORCAMENTARIO (POR_ID),
    FOREIGN KEY (EMP_PGOID) REFERENCES TB_PROGRAMA_GOVERNO (PGO_ID),
    FOREIGN KEY (EMP_AEMID) REFERENCES TB_AUTOR_EMENDA (AEM_ID),
    FOREIGN KEY (EMP_CDEID) REFERENCES TB_CATEGORIA_DESPESA (CDE_ID),
    FOREIGN KEY (EMP_GDEID) REFERENCES TB_GRUPO_DESPESA (GDE_ID),
    FOREIGN KEY (EMP_MODID) REFERENCES TB_MODALIDADE (MOD_ID),
    FOREIGN KEY (EMP_EDEID) REFERENCES TB_ELEMENTO_DESPESA (EDE_ID)
);
